@WhatShouldIPlay.Server_HostAddress = https://localhost:7202

GET {{WhatShouldIPlay.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WhatShouldIPlay.Server_HostAddress}}/hero

###

GET {{WhatShouldIPlay.Server_HostAddress}}/hero/playstyle/flank

###


GET {{WhatShouldIPlay.Server_HostAddress}}/hero/role/Duelist

###



GET {{WhatShouldIPlay.Server_HostAddress}}/hero/favorite

###


GET {{WhatShouldIPlay.Server_HostAddress}}/hero/mostPlayedHeroes/DuaLipaFan7/1

###
